### ISSUE TITLE
Check If Manual Permission Changes Are Reset by Terraform

### ISSUE THREAD

**Issue by sprankhub** [mage-os/terraform#11]
If we enable discussions on e.g. https://github.com/mage-os/mageos-magento2 manually, will this be reset by the next run of `terraform apply`?

**Comment by vitaliy-golomoziy** [comment]
As long we do not import the change into the terraform state, it should not. Even so, having a discrepancy between the terraform state and the actual state is not a great thing to have.

**Comment by Vinai** [comment]
As posted by @sprankhub on Discord, [it's not possible yet](https://github.com/integrations/terraform-provider-github/issues/627).
