### ISSUE TITLE
Branch delete permissions

### ISSUE THREAD

**Issue by rhoerr** [mage-os/terraform#21]
I'm not able to delete PR branches at https://github.com/mage-os/mage-os-website/branches since Terraform was initialized. This seems like it'll be necessary for repos under active development, to keep the branches clean.

Seems to be a side effect of the * branch restrictions on the repo.

I don't know how long the website will run from this repository with the content site merge discussions going on, so the website repo itself might not be worth a lot of specific effort at this point. But the same will probably come up for our other repos.

**Comment by sprankhub** [comment]
#22 should make sure that in the future, this happens automatically. Could you delete the current stale branches manually at this time or tell me which ones I may delete?

**Comment by rhoerr** [comment]
I don't see any change at this point, still can't delete the stale branches.

`faq` and `2022-11-02-update` are both merged and no longer relevant on https://github.com/mage-os/mage-os-website/branches .

Thanks

**Comment by sprankhub** [comment]
I deleted the branches manually.

As soon as the referenced PR is merged, GitHub should automatically delete the respective branch on merge.
