### ISSUE TITLE
New repo for mage-os contribution environments

### ISSUE THREAD

**Issue by adamzero1** [mage-os/terraform#34]
Hi,
Sorry I know I should of done this last week, please could we create a repo for development environments for mage-os, can't remember the name @Vinai wanted, think it was `development-environment`

Nice one thanks

**Comment by aleron75** [comment]
For the records, in the last tech meeting, we opted for **dev-env-gitpod**

**Comment by sprankhub** [comment]
Here you go, @adamzero1: https://github.com/mage-os/dev-env-gitpod
