### ISSUE TITLE
Add Topics

### ISSUE THREAD

**Issue by sprankhub** [mage-os/terraform#50]
Now that we support topics (see #29 / #49), we should add them for all repositories.

Which topics should all repositories have? I suggest `mage-os`, `magento2` and `adobe-commerce`.

Which topics should all mirror repositories have? I suggest `mirror`.

Should we also adopt all topics from the respective "original" repositories?

Feel free to give feedback here, but this should probably also be discussed during the next tech meeting.

**Comment by Vinai** [comment]
`mage-os`, `magento`, `magento2`, `mirror` and also repository specific topics.
