### ISSUE TITLE
Terraform actions fail with billing error

### ISSUE THREAD

**Issue by rhoerr** [mage-os/terraform#99]
https://github.com/mage-os/terraform/actions/runs/12475976313/job/34820174920

I think this came up before.

> Error: Error loading state: Failed to open state file at gs://mage-os-tf-state/terraform/state/default.tfstate: googleapi: got HTTP response code 403 with body:
```
<?xml version='1.0' encoding='UTF-8'?>
<Error>
  <Code>UserProjectAccountProblem</Code>
  <Message>The project to be billed is associated with a closed billing account.</Message>
  <Details>The billing account for the owning project is disabled in state closed</Details>
</Error>
```

**Comment by rhoerr** [comment]
@sprankhub @Vinai Able to assist?

**Comment by sprankhub** [comment]
I had a look at this. The free trial account for our Google Cloud account was expired. I now had to activate the full account. I set a budget limit of 10 PLN, so we should get a notification via e-mail whenever we use some paid services. However, it only goes to the admin e-mail - I hope someone observes it :D

**Comment by sprankhub** [comment]
I still had to import the repository, because it was already present, but now it is all green: https://github.com/mage-os/terraform/actions/runs/12475976313/job/34863747177
